'use strict';
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const crypto=require('node:crypto');
const {performance}=require('node:perf_hooks');
const protocol=require('./protocol.json');
const sourceManifest=require('./source-manifest.json');
const clone=v=>JSON.parse(JSON.stringify(v));
const sha256=v=>crypto.createHash('sha256').update(typeof v==='string'||Buffer.isBuffer(v)?v:JSON.stringify(v)).digest('hex');
function assert(ok,message){if(!ok)throw new Error(message);}
function atomicJSON(file,value){
 fs.mkdirSync(path.dirname(file),{recursive:true});
 const tmp=file+'.tmp-'+process.pid;
 const fd=fs.openSync(tmp,'w',0o600);
 try{fs.writeFileSync(fd,JSON.stringify(value,null,2)+'\n');fs.fsyncSync(fd);}finally{fs.closeSync(fd);}
 fs.renameSync(tmp,file);
}
function checkSources(repo){
 for(const[file,wanted]of Object.entries(sourceManifest)){
  const actual=sha256(fs.readFileSync(path.join(repo,file)));
  assert(actual===wanted,'BASELINE_SOURCE_MISMATCH: '+file);
 }
 return clone(sourceManifest);
}
function makeEngine(repo){
 checkSources(repo);
 const context=vm.createContext({performance});
 for(const file of['engine.js','ai-weights.js','ai.js','ai-config.js','logic-evaluator.js','ai-candidate.js','ai-release.js']){
  vm.runInContext(fs.readFileSync(path.join(repo,'public',file),'utf8'),context,{filename:'public/'+file});
 }
 const E=context.BaoEngine,AI=context.BaoReleaseAI,C=context.BaoReleaseConfig;
 assert(E&&AI&&C,'PRODUCTION_ENGINE_LOAD_FAILED');
 assert(C.GENERATION==='AI-GEN4'&&C.RELEASE_ID==='AI-GEN4-RELEASE-001','AI_RELEASE_MISMATCH');
 assert(C.displayIdentity('expert').evaluator==='PBAI-C015-v1','EVALUATOR_IDENTITY_MISMATCH');
 function baseline(state){
  const options={...C.searchOptions('expert',{hardwareConcurrency:4,deviceMemory:4},state),maxDepth:12,timeLimitMs:2000};
  assert(options.maxDepth===12&&options.timeLimitMs===2000,'EXPERT_STANDARD_MISMATCH');
  const result=AI.analyzeMove(clone(state),'expert',()=>0.5,options);
  assert(result.stats?.evaluationCandidate==='PBAI-C015-v1'&&result.stats.evaluationFallback===false,'BASELINE_EVALUATOR_MISMATCH');
  assert(result.stats.completedDepth<=12,'BASELINE_DEPTH_MISMATCH');
  const legal=E.moveVariantsForSearch(state);
  assert(legal.some(m=>AI.moveKey(m)===AI.moveKey(result.move)),'BASELINE_ILLEGAL_MOVE');
  return clone(result);
 }
 return{E,AI,C,baseline};
}
const rules={
 game:'Bao la Kiswahili, repository rules R-002; takasia is not implemented.',
 objective:'Win by emptying the opponent front row or leaving the opponent without a legal move. Seed total alone is not the objective.',
 coordinates:'pits[player][row][index]. Players are 0 and 1; row 0 is front, row 1 is back; indices 0..7. Opposing front pit has index 7-index. nyumba is front index 4.',
 phases:'namua uses reserve seeds; mtaji starts when both reserves are empty. Capture is compulsory when available. Relay sowing and house choices are already resolved in supplied exact after-states.',
 authority:'Every supplied candidate is an exact legal variant generated by the Bao engine. Supplied exact after-states, captured-seed counts, terminal flags and winners are authoritative. Do not invent or reconstruct another move.'
};
function candidateId(stateHash,move){return'c_'+sha256(protocol.id+'\n'+stateHash+'\n'+JSON.stringify(move)).slice(0,16);}
function captureCount(events){return events.filter(e=>e.kind==='capture').reduce((n,e)=>n+(Number(e.count)||0),0);}
function requestFor(engine,state){
 const legal=engine.E.moveVariantsForSearch(state);
 assert(legal.length>=2&&legal.length<=protocol.jev.choiceLimit,'CANDIDATE_COUNT_OUT_OF_RANGE');
 const stateHash=sha256(state),rows=[];
 for(const move of legal){
  const key=engine.AI.moveKey(move),id=candidateId(stateHash,move),result=engine.E.applyMoveForSearch(state,move);
  rows.push({id,key,move:clone(move),after:clone(result.state),capturedSeeds:captureCount(result.events),terminalWinner:result.state.winner,
   immediateTerminalWin:result.state.winner===state.player&&result.state.reason!=='relay-limit'});
 }
 rows.sort((a,b)=>a.id.localeCompare(b.id));
 assert(new Set(rows.map(r=>r.id)).size===rows.length,'CANDIDATE_ID_COLLISION');
 const candidates={},criteria={},moveById={};
 for(const row of rows){
  candidates[row.id]={move:row.move,after:row.after,capturedSeeds:row.capturedSeeds,terminalWinner:row.terminalWinner,immediateTerminalWin:row.immediateTerminalWin};
  criteria[row.id]='Candidate '+row.id+' in state.candidates. This supplied candidate is legal and its after-state is authoritative.';
  moveById[row.id]={move:row.move,moveKey:row.key};
 }
 const body={
  model:protocol.jev.model,
  state:{rules,rootPlayer:state.player,current:clone(state),candidates},
  questions:{move:{type:'choice',instructions:'Choose the one supplied legal candidate you would actually play for rootPlayer against a strong resisting opponent. Select exactly one supplied candidate. The supplied legal moves and exact after-states are authoritative outputs of the Bao engine. Do not invent, reconstruct, or substitute another move. Your selected candidate will be executed directly and no downstream search AI will override it. Compare the candidates using tactical judgment, strategic judgment, and future resistance. If an authoritative after-state is an immediate terminal win for rootPlayer, treat that as a completed win when choosing. Do not assume the player to move in an after-state is rootPlayer.',criteria}}
 };
 assert(Buffer.byteLength(JSON.stringify(body),'utf8')<=protocol.jev.requestByteSafetyLimit,'REQUEST_SIZE_LIMIT');
 return{body,moveById,candidateIds:rows.map(r=>r.id),stateHash,candidateSetHash:sha256(rows.map(r=>({id:r.id,key:r.key,move:sha256(r.move),after:sha256(r.after)})))};
}
function exactKeySet(a,b){const x=[...a].sort(),y=[...b].sort();return x.length===y.length&&x.every((v,i)=>v===y[i]);}
function validateResponse(data,packet){
 assert(data&&data.model===protocol.jev.model,'MODEL_MISMATCH');
 const answer=data.answers?.move,ids=packet.candidateIds;
 assert(answer?.type==='choice','RESPONSE_INVALID');
 assert(typeof answer.choice==='string'&&ids.includes(answer.choice),'RESPONSE_INVALID');
 assert(Number.isFinite(answer.confidence)&&answer.confidence>=0&&answer.confidence<=1,'RESPONSE_INVALID');
 assert(answer.probabilities&&typeof answer.probabilities==='object'&&!Array.isArray(answer.probabilities),'RESPONSE_INVALID');
 assert(exactKeySet(Object.keys(answer.probabilities),ids),'RESPONSE_INVALID');
 let total=0,max=-Infinity;
 for(const id of ids){const p=answer.probabilities[id];assert(Number.isFinite(p)&&p>=0&&p<=1,'RESPONSE_INVALID');total+=p;max=Math.max(max,p);}
 assert(Math.abs(total-1)<protocol.responses.probabilitiesMustSumToOneTolerance,'RESPONSE_INVALID');
 assert(answer.probabilities[answer.choice]+protocol.responses.probabilitiesMustSumToOneTolerance>=max,'RESPONSE_INVALID');
 const selected=packet.moveById[answer.choice];
 assert(selected,'RESPONSE_INVALID');
 return{candidateId:answer.choice,move:clone(selected.move),moveKey:selected.moveKey,confidence:answer.confidence,
  response:{model:data.model,answers:{move:{type:'choice',choice:answer.choice,confidence:answer.confidence,
   probabilities:Object.fromEntries(ids.map(id=>[id,answer.probabilities[id]]))}},usage:{}}};
}
function directDecision(engine,state,validated){
 const legal=engine.E.moveVariantsForSearch(state),key=engine.AI.moveKey(validated.move),serialized=JSON.stringify(validated.move);
 assert(key===validated.moveKey,'SELECTED_MOVE_KEY_MISMATCH');
 assert(legal.some(m=>JSON.stringify(m)===serialized),'SELECTED_MOVE_NOT_LEGAL');
 const applied=engine.E.applyMoveForSearch(state,validated.move);
 return{move:clone(validated.move),moveKey:key,after:clone(applied.state),afterHash:sha256(applied.state)};
}
function forcedDecision(engine,state){
 const legal=engine.E.moveVariantsForSearch(state);assert(legal.length===1,'NOT_FORCED');
 const move=clone(legal[0]),applied=engine.E.applyMoveForSearch(state,move);
 return{move,moveKey:engine.AI.moveKey(move),after:clone(applied.state),afterHash:sha256(applied.state)};
}
module.exports={protocol,clone,sha256,assert,atomicJSON,checkSources,makeEngine,requestFor,validateResponse,directDecision,forcedDecision,rules};
